name: Run tests in Miniconda
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: rga
          environment-file: environment.yml
          python-version: 3.8.5
          auto-activate-base: false
          
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      
      - name: run pytest
        shell: bash -l {0}
        run: pytest
          
            
