name: Run tests in Miniconda
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      
      - name: set up miniconda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: rga
          environment-file: environment.yml
          python-version: 3.8.5
          auto-activate-base: false
          
      - name: get info about conda environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
      
      - name: run pytest
        shell: bash -l {0}
        run: |
          conda install pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          directory: ./coverage/reports/
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)    
          path_to_write_report: ./coverage/codecov_report.txt
            
